from pathlib import Path
import subprocess


def find_tof_folder(root_dir: Path) -> Path:
    """
    Recursively find the TOF 3D multi-slab folder
    Excludes MIP folders.
    """
    candidates = []

    for p in root_dir.rglob("*"):
        if p.is_dir():
            name = p.name.lower()
            if (
                "tof_fl3d_tra_p2_multi-slab" in name
                and "mip" not in name
            ):
                candidates.append(p)

    if len(candidates) == 0:
        raise FileNotFoundError(
            "No 'tof_fl3d_tra_p2_multi-slab' folder found in uploaded ZIP"
        )

    # If multiple found, pick the largest (most DICOMs)
    candidates.sort(
        key=lambda x: len(list(x.glob("*.dcm"))),
        reverse=True
    )

    return candidates[0]


def run_pipeline(tmpdir: Path) -> Path:
    raw_root = tmpdir / "00_raw_dicom"
    nifti_dir = tmpdir / "01_nifti"
    vessel_dir = tmpdir / "02_vesselness"
    mask_dir = tmpdir / "03_masks"
    mesh_dir = tmpdir / "04_mesh"

    for d in [nifti_dir, vessel_dir, mask_dir, mesh_dir]:
        d.mkdir(exist_ok=True)

    # 🔍 FIND correct TOF folder automatically
    tof_dicom_dir = find_tof_folder(raw_root)

    # ----------------------------
    # DICOM → NIfTI
    # ----------------------------
    subprocess.run(
        [
            "python", "scripts/dicom_to_nifti.py",
            "-i", str(tof_dicom_dir),
            "-o", str(nifti_dir / "brain_TOF.nii.gz"),
        ],
        check=True,
    )

    # ----------------------------
    # Vesselness
    # ----------------------------
    subprocess.run(["python", "scripts/vesselness.py"], check=True)

    # ----------------------------
    # Threshold & clean
    # ----------------------------
    subprocess.run(["python", "scripts/threshold_and_clean.py"], check=True)

    # ----------------------------
    # Remove discontinuous vessels
    # ----------------------------
    subprocess.run(
        ["python", "scripts/remove_discontinuous_vessels.py"], check=True
    )

    # ----------------------------
    # Mesh
    # ----------------------------
    subprocess.run(["python", "scripts/mesh_from_mask.py"], check=True)

    stl_path = mesh_dir / "cerebral_arteries.stl"

    if not stl_path.exists():
        raise FileNotFoundError("STL file not generated by pipeline")

    return stl_path
